variables:

  # Global
  ap_vm_image: windows-2019

  location: eastus
  prefix: dops
  postfix: sc009
  environment: dev
  core: dlh

  # Azure DevOps 
  ado_service_connection_rg: Dev01-AzureSub01
  
  objectID: 469a7eb1-6b9d-4f20-a6d5-fed30d2dc293

  # IaC
  baseName: $(prefix)$(core)$(postfix)$(environment)
  resourceGroupName: rg-$(baseName) #You also need to change the ResourceGroupname in main.bicep file
  storageAccountName: st$(prefix)$(core)$(postfix)$(environment)
  dataLakeAccountName: adl$(prefix)$(core)$(postfix)$(environment)
  sqlServerName: sql-$(prefix)-$(core)-$(postfix)-$(environment)
  databaseName: sampledb
  synapseWorkspace: syn-$(prefix)-$(core)-$(postfix)-$(environment)
  synapsedatalakegen2name: adlssyn$(prefix)$(core)$(postfix)$(environment)
  keyVaultName: kv-$(prefix)-$(core)-$(postfix)-$(environment)
